[package]
name = "html_view"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
html_view_shared = { path = "../html_view_shared" }
uuid.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
